package panels;

import java.text.DateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Mehmet Karagoz
 * @since 02.03.2021
 */
public class TicketScreen extends javax.swing.JFrame {

    /**
     * Creates new form TicketScreen
     */
    String name;
    String surname;
    String goingFrom;
    String goingTo;
    String departDate;
    String returnDate;
    String sex;
    String kindOfTickets;

    public TicketScreen(String name, String surname) {
        initComponents();

        this.name = name;
        this.surname = surname;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        ticketKinda = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        lblFTitle = new javax.swing.JLabel();
        lblFName = new javax.swing.JLabel();
        lblFSurname = new javax.swing.JLabel();
        lblFGender = new javax.swing.JLabel();
        lblFFrom = new javax.swing.JLabel();
        lblFTo = new javax.swing.JLabel();
        lblFDepart = new javax.swing.JLabel();
        lblFReturn = new javax.swing.JLabel();
        lblFPrice = new javax.swing.JLabel();
        btnFCancel = new javax.swing.JButton();
        btnFBuy = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblFrom = new javax.swing.JLabel();
        cbxFromCities = new javax.swing.JComboBox<>();
        lblTo = new javax.swing.JLabel();
        cbxToCities = new javax.swing.JComboBox<>();
        dateDepart = new com.toedter.calendar.JDateChooser();
        lblDepart = new javax.swing.JLabel();
        lblDepart1 = new javax.swing.JLabel();
        dateReturn = new com.toedter.calendar.JDateChooser();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        lblMale = new javax.swing.JLabel();
        lblFemale = new javax.swing.JLabel();
        rbtnFirstClass = new javax.swing.JRadioButton();
        rbtnEconomyClass = new javax.swing.JRadioButton();
        rbtnBusinessClass = new javax.swing.JRadioButton();
        btnSearch = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame1.setTitle("Ticket Information");
        jFrame1.setBounds(new java.awt.Rectangle(425, 175, 0, 0));
        jFrame1.setMinimumSize(new java.awt.Dimension(293, 360));
        jFrame1.setPreferredSize(new java.awt.Dimension(293, 360));
        jFrame1.setSize(new java.awt.Dimension(293, 360));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        lblFTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblFTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblFTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFTitle.setText("Ticket Information");

        lblFName.setText("jLabel1");

        lblFSurname.setText("jLabel1");

        lblFGender.setText("jLabel1");

        lblFFrom.setText("jLabel1");

        lblFTo.setText("jLabel1");

        lblFDepart.setText("jLabel1");

        lblFReturn.setText("jLabel1");

        lblFPrice.setText("jLabel1");

        btnFCancel.setText("Cancel");
        btnFCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFCancelActionPerformed(evt);
            }
        });

        btnFBuy.setText("Buy");
        btnFBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFBuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblFName))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblFSurname))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblFGender))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblFFrom))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblFTo))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblFDepart))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblFReturn))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblFPrice))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblFTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnFBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFCancel)
                .addGap(16, 16, 16))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFBuy, btnFCancel});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblFTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFSurname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFGender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFFrom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFTo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFDepart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFCancel)
                    .addComponent(btnFBuy))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnFBuy, btnFCancel});

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ticket");
        setBounds(new java.awt.Rectangle(415, 170, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(171, 153, 255));

        lblFrom.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblFrom.setForeground(new java.awt.Color(0, 0, 0));
        lblFrom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/placeholder.png"))); // NOI18N
        lblFrom.setText("From : ");

        cbxFromCities.setBackground(new java.awt.Color(51, 153, 255));
        cbxFromCities.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cbxFromCities.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "Adana", "Adıyaman", "Afyon", "Ağrı", "Aksaray", "Amasya", "Ankara", "Antalya", "Ardahan", "Artvin", "Aydın", "Balıkesir", "Bartın", "Batman", "Bayburt", "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Düzce", "Edirne", "Elâzığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkâri", "Hatay", "Iğdır", "Isparta", "İstanbul", "İzmir", "Kahramanmaraş", "Karabük", "Karaman", "Kars", "Kastamonu", "Kayseri", "Kırıkkale", "Kırklareli", "Kırşehir", "Kilis", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Mardin", "Mersin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Osmaniye", "Rize", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Şanlıurfa", "Şırnak", "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Uşak", "Van", "Yalova", "Yozgat", "Zonguldak" }));

        lblTo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTo.setForeground(new java.awt.Color(0, 0, 0));
        lblTo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/destination.png"))); // NOI18N
        lblTo.setText("To :");

        cbxToCities.setBackground(new java.awt.Color(51, 153, 255));
        cbxToCities.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cbxToCities.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "Adana", "Adıyaman", "Afyon", "Ağrı", "Aksaray", "Amasya", "Ankara", "Antalya", "Ardahan", "Artvin", "Aydın", "Balıkesir", "Bartın", "Batman", "Bayburt", "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Düzce", "Edirne", "Elâzığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkâri", "Hatay", "Iğdır", "Isparta", "İstanbul", "İzmir", "Kahramanmaraş", "Karabük", "Karaman", "Kars", "Kastamonu", "Kayseri", "Kırıkkale", "Kırklareli", "Kırşehir", "Kilis", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Mardin", "Mersin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Osmaniye", "Rize", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Şanlıurfa", "Şırnak", "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Uşak", "Van", "Yalova", "Yozgat", "Zonguldak" }));

        dateDepart.setBackground(new java.awt.Color(51, 153, 255));
        dateDepart.setForeground(new java.awt.Color(255, 255, 255));
        dateDepart.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblDepart.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDepart.setForeground(new java.awt.Color(0, 0, 0));
        lblDepart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar.png"))); // NOI18N
        lblDepart.setText("Depart :");

        lblDepart1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDepart1.setForeground(new java.awt.Color(0, 0, 0));
        lblDepart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar.png"))); // NOI18N
        lblDepart1.setText("Return :");

        dateReturn.setBackground(new java.awt.Color(51, 153, 255));
        dateReturn.setForeground(new java.awt.Color(255, 255, 255));
        dateReturn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        gender.add(rbtnMale);
        rbtnMale.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rbtnMale.setForeground(new java.awt.Color(0, 0, 0));
        rbtnMale.setText("Male");
        rbtnMale.setBorder(null);
        rbtnMale.setContentAreaFilled(false);

        gender.add(rbtnFemale);
        rbtnFemale.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rbtnFemale.setForeground(new java.awt.Color(0, 0, 0));
        rbtnFemale.setText("Female");
        rbtnFemale.setBorder(null);
        rbtnFemale.setContentAreaFilled(false);

        lblMale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/male-user.png"))); // NOI18N

        lblFemale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/female-worker.png"))); // NOI18N

        ticketKinda.add(rbtnFirstClass);
        rbtnFirstClass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rbtnFirstClass.setForeground(new java.awt.Color(0, 0, 0));
        rbtnFirstClass.setText("First Class");
        rbtnFirstClass.setBorder(null);
        rbtnFirstClass.setContentAreaFilled(false);

        ticketKinda.add(rbtnEconomyClass);
        rbtnEconomyClass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rbtnEconomyClass.setForeground(new java.awt.Color(0, 0, 0));
        rbtnEconomyClass.setText("Economy Class");
        rbtnEconomyClass.setBorder(null);
        rbtnEconomyClass.setContentAreaFilled(false);

        ticketKinda.add(rbtnBusinessClass);
        rbtnBusinessClass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rbtnBusinessClass.setForeground(new java.awt.Color(0, 0, 0));
        rbtnBusinessClass.setText("Business Class");
        rbtnBusinessClass.setBorder(null);
        rbtnBusinessClass.setContentAreaFilled(false);

        btnSearch.setBackground(new java.awt.Color(102, 102, 255));
        btnSearch.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtnMale)
                                .addGap(95, 95, 95))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dateDepart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxFromCities, 0, 153, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(lblTo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblDepart1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxToCities, 0, 153, Short.MAX_VALUE)
                                    .addComponent(dateReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFemale)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnFemale)
                                    .addComponent(rbtnBusinessClass, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(111, 111, 111))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtnFirstClass)
                        .addGap(122, 122, 122)
                        .addComponent(rbtnEconomyClass, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxToCities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDepart1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxFromCities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnMale)
                            .addComponent(rbtnFemale)))
                    .addComponent(lblMale)
                    .addComponent(lblFemale))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnFirstClass)
                    .addComponent(rbtnEconomyClass)
                    .addComponent(rbtnBusinessClass))
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        goingFrom = (String) cbxFromCities.getSelectedItem();
        goingTo = (String) cbxToCities.getSelectedItem();

        if (goingFrom.equals("<none>") || goingTo.equals("<none>")) {
            JOptionPane.showMessageDialog(this, "Please choose the city.");
            return;
        }

        if (dateDepart.getDate() == null || dateReturn.getDate() == null) {

            JOptionPane.showMessageDialog(this, "Please choose the date.");
            return;
        }
        departDate = DateFormat.getInstance().format(dateDepart.getDate());
        returnDate = DateFormat.getInstance().format(dateReturn.getDate());

        if (rbtnMale.isSelected()) {
            sex = "Male";
        } else if (rbtnFemale.isSelected()) {
            sex = "Female";
        } else {
            sex = null;
            JOptionPane.showMessageDialog(this, "Please choose the gender.");
            return;
        }

        String price;
        if (rbtnFirstClass.isSelected()) {
            kindOfTickets = "First Class";
            price = "200";

        } else if (rbtnEconomyClass.isSelected()) {
            kindOfTickets = "Economy Class";
            price = "150";

        } else if (rbtnBusinessClass.isSelected()) {
            kindOfTickets = "Business Class";
            price = "300";
        } else {
            kindOfTickets = null;
            JOptionPane.showMessageDialog(this, "Please choose the ticket class");
            return;
        }

        lblFName.setText("Name : " + name);
        lblFSurname.setText("Surname : " + surname);
        lblFGender.setText("Gender : " + sex);
        lblFFrom.setText("From : " + goingFrom);
        lblFTo.setText("To : " + goingTo);
        lblFDepart.setText("Depart : " + departDate);
        lblFReturn.setText("Return : " + returnDate);
        lblFPrice.setText("Price : " + price);

        jFrame1.setVisible(true);

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnFBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFBuyActionPerformed
        JOptionPane.showMessageDialog(this, "Thank you for choosing us.");
        this.setVisible(false);
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnFBuyActionPerformed

    private void btnFCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFCancelActionPerformed
        jFrame1.setVisible(false);
        jFrame1.dispose();
    }//GEN-LAST:event_btnFCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TicketScreen().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFBuy;
    private javax.swing.JButton btnFCancel;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbxFromCities;
    private javax.swing.JComboBox<String> cbxToCities;
    private com.toedter.calendar.JDateChooser dateDepart;
    private com.toedter.calendar.JDateChooser dateReturn;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDepart;
    private javax.swing.JLabel lblDepart1;
    private javax.swing.JLabel lblFDepart;
    private javax.swing.JLabel lblFFrom;
    private javax.swing.JLabel lblFGender;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblFPrice;
    private javax.swing.JLabel lblFReturn;
    private javax.swing.JLabel lblFSurname;
    private javax.swing.JLabel lblFTitle;
    private javax.swing.JLabel lblFTo;
    private javax.swing.JLabel lblFemale;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblMale;
    private javax.swing.JLabel lblTo;
    private javax.swing.JRadioButton rbtnBusinessClass;
    private javax.swing.JRadioButton rbtnEconomyClass;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnFirstClass;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.ButtonGroup ticketKinda;
    // End of variables declaration//GEN-END:variables
}
